config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  
  resources :author_sessions, only: [ :new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

  get 'months', to: 'months#index'
  resources :months





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :views
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300*300>", thumb: "100*100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :title, :body, presence: true

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

  def view_count

  end


end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Article Saved Successfully!'
    else
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = 'Article Deleted Successfully!'
    else
      flash[:alert] = 'Article cannot be deleted!'
    end
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end




end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save
    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @article_days = Article.all.group_by{ |r| r.created_at }
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]

  def index
    @tag = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

end

app/controllers/view_controller.rb
class ViewController < ApplicationController
  def show
    @article.view_count += 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/view_helper.rb
module ViewHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_comment.html.haml
%div
  %h4
    Comment by #{comment.author_name}
  %p.comment= comment.body
  %p
    Posted #{distance_of_time_in_words(comment.article.created_at, comment.created_at)} later

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %><br/>
  </p>

  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach an Image" %><br/>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_form.html.haml
.row
  .col-sm-12
    = form_for(@article, html: {multipart: true}) do |f|
      - if @article.errors.present?
        %ul.alert.alert-danger
          - @article.errors.full_messages.each do |error|
            %li= error
        %br
      .row
        .col-sm-3.form-group
          = f.label :title
        .col-sm-6.form-group
          = f.text_field :title, class: 'form-control', required: true

      .row
        .col-sm-3.form-group
          = f.label :body
        .col-sm-6.form-group
          = f.text_area :body, rows: 10, class: 'form-control', required: true

      .row
        .col-sm-3.form-group
          = f.label :tag_list
        .col-sm-6.form-group
          = f.text_field :tag_list, class: 'form-control'

      .row
        - if @article.image.exists?
          = image_tag @article.image.url
        .col-sm-3.form-group
          = f.label :image, "Attach an Image"
        .col-sm-6.form-group
          = f.file_field :image

      .row
        .col-md-12= f.submit 'Submit', class: 'btn btn-primary'

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

<% @article_months.sort.each do |pub, articles| %>
  <h3><%= pub.strftime('%B') %></h3>
  <% for article in articles %>
    <%= link_to "#{article.title}", article_path(article) %>
  <% end %>
<% end %>

app/views/articles/edit.html.haml
%h1.form-group Edit article

= render 'form'

app/views/articles/index.html.erb
<nav>
  <%= link_to "January", months_path %>
  <%= link_to "Feburary", months_path %>
  <%= link_to "March", months_path %>
  <%= link_to "April", months_path %>
  <%= link_to "May", months_path %>
  <%= link_to "June", months_path %>
  <%= link_to "July", months_path %>
  <%= link_to "August", months_path %>
  <%= link_to "September", months_path %>
  <%= link_to "October", months_path %>
  <%= link_to "November", months_path %>
  <%= link_to "December", months_path %>
</nav>

<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article_path(article) %>
  </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/index.html.haml
- @articles.each do |article|
  %h1= link_to article.title, article_path(article)
  %em= article.created_at.strftime("%Y-%m-%d %I:%m %p")
  %div= article.body
  %hr

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render partial: 'form' %>

app/views/articles/new.html.haml
%h1.form-group Create a new article

= render partial: 'form'

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url %>
  <% end %>
</p>
<p><%= @article.body %></p>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>
  Views:
  
</p>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comments/form' %>

<% if logged_in? %>

<%= link_to "<<Back to Articles List", articles_path %><br/>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %><br/>
<%= link_to "edit", edit_article_path(@article) %>

<% end %>

app/views/articles/show.html.haml
%h1= @article.title
%p
  - if @article.image.exists?
    = image_tag @article.image.url
%p= @article.body
%p
  Tags:
  - @article.tags.each do |tag|
    = link_to tag.name, tag_path(tag)
%p
  Views:
  (#{@view_count = Article.count.size})
%h3
  Comments (#{@article.comments.size})
= render partial: 'comments/form'
.navbar
  .ul.nav.navbar-nav
    - if logged_in?
      %li.nav-item
        = link_to "<<Back to Articles List", articles_path
      %li.nav-item
        = link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
      %li.nav-item
        = link_to "edit", edit_article_path(@article)

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/_form.html.haml
= form_for(author) do |f|
  - if author.errors.any?
    #error_explanation
      %h2
        = pluralize(author.errors.count, 'error')
        prohibited this author from being saved:
      %ul
        - author.errors.full_messages.each do |message|
          %li= message
  .row.col-sm-offset-1
    .col-sm-2.form-group
      = f.label :username
    .col-sm-6
      = f.text_field :username, placeholder: 'username', class: 'form-control', required: true

  .row.col-sm-offset-1
    .col-sm-2.form-group
      = f.label :email
    .col-sm-6
      = f.text_field :email, placeholder: 'email', class: 'form-control', required: true

  .row.col-sm-offset-1
    .col-sm-2.form-group
      = f.label :password
    .col-sm-6
      = f.password_field :password, placeholder: 'password', class: 'form-control', required: true

  .row.col-sm-offset-1
    .col-sm-2.form-group
      = f.label :password_confirmation
    .col-sm-6
      = f.password_field :password_confirmation, placeholder: 'password_confirmation', class: 'form-control', required: true

  .row.col-sm-offset-1
    .col-sm-12.form-group= f.submit 'Submit', class: 'btn btn-primary'

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/edit.html.haml
%h1.form-group.col-sm-offset-4 Editing Author
%br
= render 'form', author: @author

#navbar
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to 'Show', @author
    %li.nav-item
      = link_to 'Back', authors_path

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/index.html.haml
%h1 Authors

.table-responsive
  %table.table
    %thead
      %tr
        %th Username
        %th Email
        %th{:colspan => '3'}

    %tbody
      - @authors.each do |author|
        %tr
          %td= author.username
          %td= author.email
          %td= link_to 'Show', author
          %td= link_to 'Edit', edit_author_path(author)
          %td= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/new.html.haml
%h1 New Author

= render 'form', author: @author

= link_to 'Back', authors_path

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.haml
%p#notice= notice
.table-responsive
  %table.table
    %thead
      %tr
        %th Username
        %th Email
    %tbody
      %tr
        %td= @author.username
        %td= @author.email

#navbar
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to 'Edit', edit_author_path(@author)
    %li.nav-item
      = link_to 'Back', authors_path

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %><br/>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %><br/>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/comments/_form.html.haml
%h3 Post a Comment

= form_for [ @article, @comment] do |f|
  .row.col-sm-8
    .col-sm-4.form-group
      = f.label :author_name, "Your Name"
    .col-sm-6
      = f.text_field :author_name, class: 'form-control'

  .row.col-sm-8
    .col-sm-4.form-group
      = f.label :author_name, "Your Comment"
    .col-sm-6
      = f.text_area :body, class: 'form-control'

  .row.col-sm-offset-0.form-group
    .col-md-10= f.submit 'Submit', class: 'btn btn-primary'

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tag.each do |tag| %>
  <li>
    <%= link_to tag.name, tag_path(tag) %>
  </li>
  <% end %>
</ul>

<%= link_to "Create a New Tag", new_tag_path, class: "new_tag" %>

app/views/tags/index.html.haml
%h1 All Tags
%ul#tags
  - @tag.each do |tag|
    %li
      = link_to tag.name, tag_path(tag)

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<% if logged_in? %>

<%= link_to "delete", article_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"} %><br/>
<%= link_to "edit", edit_article_path(@tag) %>

<% end %>

app/views/tags/show.html.haml
%h1
  Articles Tagged with #{@tag.name}
%ul
  - @tag.articles.each do |article|
    %li= link_to article.title, article_path(article)
#navbar
  %ul.nav.navbar-nav
    - if logged_in?
      %li.nav-item
        = link_to "<<Back to Tags List", tags_path
      %li.nav-item
        = link_to "Delete", article_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"}
      %li.nav-item
        = link_to "Edit", edit_article_path(@tag)