config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  
  resources :author_sessions, only: [ :new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

  get 'months', to: 'months#index'
  resources :months





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :views
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300*300>", thumb: "100*100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :title, :body, presence: true

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

  def view_count

  end


end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :article
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Article Saved Successfully!'
    else
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = 'Article Deleted Successfully!'
    else
      flash[:alert] = 'Article cannot be deleted!'
    end
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end




end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @article_days = Article.all.group_by{ |r| r.created_at }
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]

  def index
    @tag = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

end

app/controllers/view_controller.rb
class ViewController < ApplicationController
  def show
    @article.view_count += 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/view_helper.rb
module ViewHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Blogger', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li.nav-item
            = link_to 'New Author', new_author_path
          %li.nav-item
            = link_to 'New Article', new_article_path
          %li.nav-item
            = link_to "Logged in as #{current_user.email}", 'javascript:void(0);'
          %li.nav-item
            = link_to 'Logout', logout_path

        - unless logged_in?
          %li.nav-item
            = link_to 'Login', login_path

app/views/layouts/_sidebar.html.haml
%h4 Archives
%ol.list-unstyled
  %li
    =link_to 'January', months_path
  %li
    =link_to 'Feburary', months_path
  %li
    =link_to 'March', months_path
  %li
    =link_to 'April', months_path
  %li
    =link_to 'May', months_path
  %li
    =link_to 'June', months_path
  %li
    =link_to 'July', months_path
  %li
    =link_to 'August', months_path
  %li
    =link_to 'September', months_path
  %li
    =link_to 'October', months_path
  %li
    =link_to 'November', months_path
  %li
    =link_to 'December', months_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash">
      <%= flash.notice %>
    </p>
    <div id="container">
      <div id="content">
        <%= yield %>
        <hr>
        <h6>
          <% if logged_in? %>
            <%= "Logged in as #{current_user.email}" %>
            <%= link_to "(logout)", logout_path %>
          <% else %>
            <%= link_to "(login)", login_path %>
          <% end %>
        </h6>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blogger
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

  %body
    .container
      = render 'layouts/header'
      -# = flash.messages.inspect
      - if flash.keys.present?
        - css = 'info'
        - if flash.keys.include?('notice')
          - css = 'success'
        - elsif flash.keys.include?('alert')
          - css = 'danger'

        %div{class: "alert alert-#{css} alert-dismissable"}
          %a.close{"aria-label" => "close", "data-dismiss" => 'css', :href => "#"} ×
          = flash[flash.keys.first.to_sym]

      .row
        - if request.original_url == login_url
          .col-sm-12= yield
        - else
          .col-sm-9= yield
          .col-sm-3= render 'layouts/sidebar'

      %footer
        %hr
        Copyright &copy; 2017.
        = link_to 'About', '#'
        |
        = link_to 'Privacy Policy', '#'